Repository proyectos-tsdwad/programador-web-proyecto-final, pull requests merged in 2023-05, with the labels that each got.

#93 Us57
  Front/src/app/app-routing.module.ts
  Front/src/app/models/book/book-model.ts
  Front/src/app/modules/book/book-card/book-card.component.css
  Front/src/app/modules/book/book-card/book-card.component.html
  Front/src/app/modules/book/book-card/book-card.component.ts
  Front/src/app/modules/common-layouts/footer/footer.component.css
  Front/src/app/modules/common-layouts/footer/footer.component.html
  Front/src/app/pages/book/book-detail-page/book-detail.component.css
  Front/src/app/pages/book/book-detail-page/book-detail.component.html
  Front/src/app/pages/book/book-detail-page/book-detail.component.ts
  Front/src/app/pages/book/book.module.ts
  Front/src/app/pages/home/home-page/home-page.component.html
  Front/src/app/pages/pages-routing.module.ts
  Front/src/app/pages/pages.module.ts
  Front/src/app/services/book/book-simulation-data.ts
  Front/src/app/services/book/book.service.ts
  Front/src/assets/img/book-cover/boulevard.png
  Front/src/assets/img/book-cover/buscando-a-dorothy.png
  Front/src/assets/img/book-cover/el-camino-del-artista.png
  Front/src/assets/img/book-cover/heartstopper.png
  Front/src/assets/img/book-cover/la-casa-de-las-grietas.png
  Front/src/assets/img/book-cover/la-teoria-de-lo-perfecto.png
  Front/src/assets/img/book-cover/pensar-a-la-japonesa.png
  Front/src/assets/img/book-cover/prisionero.png
  Front/src/assets/img/book-cover/punk-57.png
  Front/src/assets/img/book-cover/sanar-la-herida.png
  Front/src/assets/img/book-cover/sigue-mi-voz.png
  Front/src/assets/img/book-cover/todo-por-volver-a-verte.png
  Front/src/assets/img/book-cover/un-cuento-perfecto.png
  Front/src/assets/img/book-cover/un-linaje-oscuro.png
  Front/src/assets/img/book-cover/violeta.png
  Front/src/styles.css
Labels: Frontend

#97 add use cases
  Documentación/Casos de uso.pdf
Labels: documentation

#99 add login-page component
  Front/src/app/modules/common-layouts/navbar/navbar.component.html
  Front/src/app/modules/common-layouts/navbar/navbar.component.ts
  Front/src/app/modules/login/login-page/login-page.component.css
  Front/src/app/modules/login/login-page/login-page.component.html
  Front/src/app/modules/login/login-page/login-page.component.spec.ts
  Front/src/app/modules/login/login-page/login-page.component.ts
  Front/src/app/modules/login/login.module.ts
  Front/src/assets/img/img utils/log-in-image.png
Labels: Frontend

#100 add register-page
  Front/src/app/modules/common-layouts/navbar/navbar.component.html
  Front/src/app/modules/common-layouts/navbar/navbar.component.ts
  Front/src/app/modules/login/login-page/login-page.component.html
  Front/src/app/modules/login/login-page/login-page.component.ts
  Front/src/app/modules/login/login.module.ts
  Front/src/app/modules/login/register-page/register-page.component.css
  Front/src/app/modules/login/register-page/register-page.component.html
  Front/src/app/modules/login/register-page/register-page.component.spec.ts
  Front/src/app/modules/login/register-page/register-page.component.ts
  Front/src/assets/img/img utils/register-image.png
Labels: Frontend

#105 add checkout-page component
  Front/src/app/pages/checkout/checkout-page/checkout-page.component.css
  Front/src/app/pages/checkout/checkout-page/checkout-page.component.html
  Front/src/app/pages/checkout/checkout-page/checkout-page.component.spec.ts
  Front/src/app/pages/checkout/checkout-page/checkout-page.component.ts
  Front/src/app/pages/checkout/checkout.module.ts
  Front/src/app/pages/pages-routing.module.ts
  Front/src/app/pages/pages.module.ts
  Front/src/assets/img/stepper/american-color.png
  Front/src/assets/img/stepper/check-sale.png
  Front/src/assets/img/stepper/master-color.png
  Front/src/assets/img/stepper/visa-color.png
Labels: Frontend

#177 Us131
  Front/db.json
  Front/src/app/models/auth/auth-model.ts
  Front/src/app/modules/layout/navbar/navbar.component.html
  Front/src/app/modules/layout/navbar/navbar.component.ts
  Front/src/app/modules/login/login-page/login-page.component.ts
  Front/src/app/services/auth/auth.service.ts
Labels: Frontend

#181 Us157
  Back/Scripts/Libreria/libreria_franklin/admin.py
  Back/Scripts/Libreria/libreria_franklin/models.py
Labels: Backend
